server:
  port: 8062
spring:
  profiles:
    active: dev
  application:
    name: ms-member
seata:
  tx-service-group: tx_group_member
info:
  app:
    name: ${spring.application.name}
    version: "1"
    description: ${spring.application.name}