server:
  port: 8098
  servlet:
    context-path: /
    session:
      cookie:
        name: SSCOOKIE
spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
    cache: true
    charset: UTF-8
logging:
  level:
    org.springframework: info