# 路由配置

# org.springframework.cloud.gateway.handler.predicate
# org.springframework.cloud.gateway.filter

### 新增/更新服务
POST http://127.0.0.1:9091/route/update
Content-Type: application/json

{
  "id": "api-order-srv",
  "predicates": [
    {
      "name": "Path",
      "args": {
        "pattern": "/api/**"
      }
    }
  ],
  "uri": "lb://ms-provider",
  "filters": [
    {
      "name": "RequestRateLimiter",
      "args": {
        "key-resolver": "#{@myKeyResolver}",
        "redis-rate-limiter.burstCapacity": 20,
        "redis-rate-limiter.replenishRate": 5
      }
    },
    {
      "name": "StripPrefix",
      "args": {
        "parts": 1
      }
    },
    {
      "name": "Hystrix",
      "args": {
        "name": "default",
        "fallbackUri": "forward:/defaultfallback"
      }
    }
  ]
}
### RequestRateLimiter 限流，需要定义key-resolver的bean
  # burstCapacity 令牌桶总容量
  # replenishRate 令牌桶每秒填充平均速率
### StripPrefix 去除URI前parts项，如/api/get => /get
### Hystrix 熔断降级

# Header类型
#"predicates": [
#    {
#      "name": "Header",
#      "args": {
#        "header": "X-VER",
#        "regexp": "[1]"
#      }
#    }
#  ]

### 新增服务
POST http://127.0.0.1:9091/route/add
Content-Type: application/json

{
}

### 删除路由
GET http://127.0.0.1:9091/route/delete/api-order-srv

### 路由表
GET http://127.0.0.1:9091/actuator/gateway/routes


### 测试
### 测试1
GET http://127.0.0.1:9091/api/order?userId=1&productId=2
X-VER: 2

### 测试2
GET http://127.0.0.1:9091/api/getUserById/1

### 测试3
POST http://127.0.0.1:9091/api/post
Content-Type: application/json

{
  "id": 1,
  "nickname": "xxx",
  "money": 100.0,
  "phone": "133xxxxxxxx"
}